src/entity/Classification.java
package entity;

import java.io.Serializable;

public class Classification implements Serializable {

    private int id;
    private String name;

    public Classification(String name){
        this.name = name;
    }


    public Classification(int id, String name){
        this.id = id;
        this.name = name;
    }

    public int getIdClassification(){
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setId(int id) {
        this.id = id;
    }
}

src/entity/Product.java
package entity;

import java.io.Serializable;

public class Product implements Serializable {

    private int id;
    private String name;
    private int amount;
    private Classification classification;

    public Product(String name, int amount, Classification classification){
        this.name=name;
        this.amount=amount;
        this.classification=classification;
    }
    public Product(int id,String name, int amount, Classification classification){
        this.id=id;
        this.name=name;
        this.amount=amount;
        this.classification=classification;
    }

    public long getId_product() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getAmount() {
        return amount;
    }

    public Classification getClassification() {
        return classification;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public void setClassification(Classification classification) {
        this.classification = classification;
    }
}

api/src/main/java/com/vironit/api/controller/ProductController.java
package com.vironit.api.controller;


import com.vironit.api.models.ProductModel;
import com.vironit.api.service.ProductService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/apteka/product")
public class ProductController {

    @Autowired
    ProductService productService;

    @RequestMapping(value = "/products", method = RequestMethod.GET)
    public ResponseEntity<List<ProductModel>> getAllProducts(@RequestParam(value = "numberPage") int numberPage) {
        return ResponseEntity.ok(productService.findAll(numberPage));
    }



    @RequestMapping(value = "/search", method = RequestMethod.GET)
    public ResponseEntity<List<ProductModel>> searchProduct(@RequestParam(value = "name",  required = false) String name,
                                                            @RequestParam(value = "id",  required = false) Integer id,
                                                            @RequestParam(value = "min",  required = false) Integer minPrice,
                                                            @RequestParam(value = "max",  required = false) Integer maxPrice){
        if(id == null) id = 0;
        if(minPrice==null) minPrice = 1;
        if (maxPrice==null) maxPrice = 1000000000;
        return  ResponseEntity.ok(productService.searchProduct(name,id,minPrice,maxPrice));
    }

    @RequestMapping(value = "/sort", method = RequestMethod.GET)
    public ResponseEntity<List<ProductModel>> sortProduct(@RequestParam(value = "id",  required = false) Integer idClassif,
                                                            @RequestParam(value = "asc",  required = false, defaultValue = "false") Boolean asc,
                                                            @RequestParam(value = "min",  required = false, defaultValue = "false") Boolean minPrice,
                                                            @RequestParam(value = "max",  required = false, defaultValue = "false") Boolean maxPrice){
        if(idClassif == null) idClassif = 0;


        return  ResponseEntity.ok(productService.sortProduct(idClassif ,asc ,minPrice,maxPrice));
    }



}

be/src/main/java/com/vironit/backend/controller/ProductController.java
package com.vironit.backend.controller;

import com.vironit.backend.service.ProductService;
import com.vironit.backend.entity.Product;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;

import java.util.List;


@RestController
@RequestMapping("/be/apteka/product/")
public class ProductController {

    private final ProductService productService;

    @Autowired
    public ProductController(ProductService productService) {
        this.productService = productService;
    }


    @RequestMapping(value = "/products", method = RequestMethod.GET)
    public List<Product> getAllProduct(@RequestParam(value = "numberPage") int numberPage){
        return productService.allProducts(numberPage);
    }

    @RequestMapping(value = "/search", method = RequestMethod.GET)
    public List<Product> getProductByParam(@RequestParam(value = "name") String name,
                                          @RequestParam(value = "id") Integer id,
                                          @RequestParam(value = "min") Integer minPrice,
                                          @RequestParam(value = "max") Integer maxPrice){
        if(id == 0) id = null;
        return productService.findProduct(name,id,minPrice,maxPrice);
    }



    @RequestMapping(value = "/getbyid/{id}", method = RequestMethod.GET)
    public Product getProductById(@PathVariable(name = "id") Integer id){
        return productService.getProductById(id);
    }

    @RequestMapping(value = "/sort", method = RequestMethod.GET)
    public List<Product> sortProduct(@RequestParam(name = "id") Integer idClassif,
                                     @RequestParam(name = "asc") Boolean asc,
                                     @RequestParam(name = "pricemin") Boolean priceAsc,
                                     @RequestParam(name = "pricemax") Boolean priceDesc){
        if(idClassif == 0) idClassif = null;
        return productService.sortProduct(idClassif, asc, priceAsc, priceDesc);
    }

}

src/servlets/product/CreateProductServlet.java
package servlets.product;

import entity.Classification;
import entity.Product;
import dao.ClassificationDao;
import dao.ProductDao;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.ArrayList;

@WebServlet("/product/create")
public class CreateProductServlet extends HttpServlet {

    ClassificationDao classificationDao = new ClassificationDao();
    ProductDao productDao = new ProductDao();

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        ArrayList<Classification> classifications = classificationDao.selectAll();
        request.setAttribute("classific",classifications);
        getServletContext().getRequestDispatcher("/product/create.jsp").forward(request, response);

    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        try {
            String name = request.getParameter("name");
            int amount = Integer.parseInt(request.getParameter("amount"));
            int idClassific = Integer.parseInt(request.getParameter("classific"));
            Classification classification = classificationDao.selectOne(idClassific);
            Product product = new Product(name, amount, classification);
            productDao.insert(product);
            response.sendRedirect(request.getContextPath()+"/product");
        }
        catch(Exception ex) {
            ex.printStackTrace();
            getServletContext().getRequestDispatcher("product/create.jsp").forward(request, response);
        }
    }
}

src/servlets/product/DeleteProductServlet.java
package servlets.product;

import dao.ClassificationDao;
import dao.ProductDao;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@WebServlet("/product/delete")
public class DeleteProductServlet extends HttpServlet {
    ProductDao productDao = new ProductDao();
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        try {
            int id = Integer.parseInt(request.getParameter("id"));
            productDao.delete(id);
            response.sendRedirect(request.getContextPath() + "/product");
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

    }
}

src/servlets/product/EditProductServlet.java
package servlets.product;

import entity.Classification;
import entity.Product;
import dao.ClassificationDao;
import dao.ProductDao;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.ArrayList;

@WebServlet("/product/edit")
public class EditProductServlet extends HttpServlet {
    ClassificationDao classificationDao = new ClassificationDao();
    ProductDao productDao = new ProductDao();
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        try {
            int id = Integer.parseInt(request.getParameter("id"));
            String name = request.getParameter("name");
            int amount = Integer.parseInt(request.getParameter("amount"));
            int idClassif = Integer.parseInt(request.getParameter("classific"));
            Classification classification = classificationDao.selectOne(idClassif);
            Product product = new Product(id, name, amount, classification);
            productDao.update(product);
            response.sendRedirect(request.getContextPath() + "/product");
        }
        catch(Exception ex) {

            getServletContext().getRequestDispatcher("/index.jsp").forward(request, response);
        }
    }


    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        try {
            int id = Integer.parseInt(request.getParameter("id"));
            Product product = productDao.selectOne(id);
            ArrayList<Classification> classifications = classificationDao.selectAll();
            request.setAttribute("classific" , classifications);
            if(product!=null) {
                request.setAttribute("product", product);
                getServletContext().getRequestDispatcher("/product/edit.jsp").forward(request, response);
            }
            else {
                getServletContext().getRequestDispatcher("/index.jsp").forward(request, response);
            }
        }
        catch (ServletException e){
            e.printStackTrace();
        }


    }
}

src/servlets/product/ProductServlet.java
package servlets.product;

import entity.Classification;
import entity.Product;
import dao.ClassificationDao;
import dao.ProductDao;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.ArrayList;

public class ProductServlet extends HttpServlet {
    ClassificationDao classificationDao = new ClassificationDao();
    ProductDao productDao = new ProductDao();

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        ArrayList<Product> products = productDao.selectAll();
        req.setAttribute("products", products);
        ArrayList<Classification> classifications = classificationDao.selectAll();
        req.setAttribute("classifications", classifications);
        try {
            getServletContext().getRequestDispatcher("/product/product.jsp").forward(req, resp);
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }
}

src/servlets/product/SearchandSortProductServlet.java
package servlets.product;

import entity.Classification;
import entity.Product;
import dao.ClassificationDao;
import dao.ProductDao;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.ArrayList;

@WebServlet("/product/search")
public class SearchandSortProductServlet extends HttpServlet {

    ClassificationDao classificationDao = new ClassificationDao();
    ProductDao productDao = new ProductDao();

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String check1 = request.getParameter("check1");
        String check2 = request.getParameter("check2");
        int id = Integer.parseInt(request.getParameter("classific"));
        ArrayList<Classification> classifications = classificationDao.selectAll();
        request.setAttribute("classifications", classifications);

        try {
            if (check1 != null && check2 == null) {
                String name = request.getParameter("name");

                ArrayList<Product> products = productDao.findByName(name);

                if (products.isEmpty()) {
                    getServletContext().getRequestDispatcher("/index.jsp").forward(request, response);
                } else {
                    request.setAttribute("products", products);
                    getServletContext().getRequestDispatcher("/product/product.jsp").forward(request, response);
                }
            }
            if(check1 !=null && check2 != null){
                String name = request.getParameter("name");
                ArrayList<Product> products =  productDao.findByNameAndClassification(name,id);
                if (products.isEmpty()) {
                    getServletContext().getRequestDispatcher("/index.jsp").forward(request, response);
                } else {
                    request.setAttribute("products", products);
                    getServletContext().getRequestDispatcher("/product/product.jsp").forward(request, response);
                }
            }
            else {
                ArrayList<Product> products = productDao.findByClassification(id);
                if (products.isEmpty()) {
                    getServletContext().getRequestDispatcher("/index.jsp").forward(request, response);
                } else {
                    request.setAttribute("products", products);
                    getServletContext().getRequestDispatcher("/product/product.jsp").forward(request, response);
                }
            }
        } catch (ServletException e) {
            e.printStackTrace();
        }

    }
}

web/product/create.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Create product</title>
</head>
<body>
<h3>New product</h3>
<form method="post">
    <label>Name</label><br>
    <input name="name" maxlength="45"/><br><br>
    <label>Amount</label><br>
    <input name="amount" type="number" min="100"  /><br><br>
    <label>Classification</label><br><br>
    <select name="classific">
        <c:forEach var="classif" items="${classific}">
            <option value=${classif.idClassification}>${classif.name}</option>
        </c:forEach>
    </select>
    <br><br>
    <button type="submit">Add product</button>
</form>
</body>
</html>

web/product/edit.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Create product</title>
</head>
<body>
<h3>New product</h3>
<form method="post">
    <input type="hidden" name="id" value="${product.id_product}">
    <label>Name</label><br>
    <input name="name" maxlength=45 value=${product.name} /><br><br>
    <label>Amount</label><br>
    <input name="amount" type="number" min="100" value=${product.amount} /><br><br>
    <label>Classification</label><br><br>
    <select name="classific">
        <c:forEach var="classif" items="${classific}">
            <option value=${classif.idClassification}>${classif.name}</option>
        </c:forEach>
    </select>
    <br><br>
    <button type="submit">Edit product</button>
</form>
</body>
</html>

web/product/product.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link href="<c:url value="/bootstrap-4.3.1/dist/css/bootstrap.min.css"/>" rel="stylesheet">

</head>
<body>
<div>
<p><a href='<c:url value="/product/create" />'>Create new</a></p>
        <form action='<c:url value="/product/search" />'>
            <div class="form-group row">
                <div class="col-4">
                    <label>Search by name</label>
                    <input type="text" class="form-control" name="name">
                </div>
                <div class="col-8">
                    <div class="form-check" style="margin-top: 6%">
                        <input class="form-check-input" type="checkbox" id="gridCheck1" name="check1">
                        <label class="form-check-label" for="gridCheck1">
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                <select name="classific" id="select_" class="form-control">
                    <c:forEach var="classif" items="${classifications}">
                        <option value=${classif.idClassification}>
                                ${classif.name}
                        </option>
                    </c:forEach>
                </select>
                </div>
                <div class="col-8">
                    <div class="form-check" style="margin-top: 1%">
                        <input class="form-check-input" type="checkbox" id="gridCheck2" name="check2">
                        <label class="form-check-label" for="gridCheck2">
                        </label>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-success" onclick="getValue()">Search</button>
        </form>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Classification</th>
        <th></th>
        <th></th>
    </tr>
    <c:forEach var="product" items="${products}">
        <tr>
            <td>${product.id_product}</td>
            <td>${product.name}</td>
            <td>${product.amount}</td>
            <td>${product.classification.name}</td>
            <td>
                <a href='<c:url value="/product/edit?id=${product.id_product}" />'>Edit</a>
            </td>
            <td>
                <form method="post" action='<c:url value="/product/delete" />' style="display:inline;">
                    <input type="hidden" name="id" value="${product.id_product}">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>

        </tr>
    </c:forEach>
</table>
<script>
    function getValue() {
        var select = document.getElementById("select_");
        var value = select.value;
        document.location.href = "/sort?id=1";

    }
</script>
</div>
</body>

</html>

web/product/sort.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: Дмитрий
  Date: 17.06.2019
  Time: 16:01
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<table>
    <tr><th>Id</th><th>Name</th><th>Amount</th><th>Classification</th></tr><th></th>
    <c:forEach var="product" items="${products}">
        <tr>
            <td>${product.id_product}</td>
            <td>${product.name}</td>
            <td>${product.amount}</td>
            <td>${product.classification.name}</td>
        </tr>
    </c:forEach>
</table>
</body>
</html>